version: "3.3"  # optional since v1.27.0
services:
  spring:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - database
  frontend:
    build: ../todo-app
    ports:
      - "80:3000"
  database:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=ryan
      - POSTGRES_DB=dev
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgressData:/var/lib/postgresql/data
volumes:
  postgressData: {}